# for a camera
name: Left
task: Calibration
img_path: /root
save_path: /root
save_prefix: test
intrinsic_parameter: 
  fx: 1.
  fy: 1.
  cx: 1.
  cy: 1.
  matrix: 
    - 
      - 1
      - 0
      - 0
    -
      - 0
      - 1
      - 0
    -
      - 0
      - 0 
      - 1
extrinsic_parameter:
  R: 
    - 
      - 1
      - 0
      - 0
    -
      - 0 
      - 1
      - 0
    -
      - 0
      - 0 
      - 1
  t: 
    - 
      - 1
    -
      - 0.3
    -
      - 0.5
  matrix: 
    - 
      - 1
      - 0
      - 0
    -
      - 0 
      - 1
      - 0
    -
      - 0
      - 0 
      - 1
    -
      - 0
      - 0
      - 0
distortion: 
  - 0
  - 0
  - 0
  - 0
  - 0