Camera:
  name: 'Basic'
  task: 'Calibration'
  img_path: ''
  save_path: ''
  save_prefix: ''
  intrinsic_parameter: 
    fx: 1.
    fy: 1.
    cx: 1.
    cy: 1.
    matrix: [[1,0,1],[0,1,1],[0,0,0]]
  extrinsic_parameter:
    R: [[],[],[]]
    t: []
    matrix: [] 